CREATE PROC PROFIT_LOSS_REPORT
AS
BEGIN
	BEGIN TRY
		SELECT
		  *,
		  (EARNINGS.EARNEDAMOUNT - EXPENSES.SPENDAMOUNT) AS PROFIT
		FROM
		  (
			SELECT
			  C.CUSTOMERID,
              SUM(PKG.RATE) EARNEDAMOUNT
			FROM
			  CUSTOMERS C
			  JOIN MONTHLYCOLLECTION MC ON C.CUSTOMERID = MC.CUSTOMERID
			  JOIN PACKAGES PKG ON C.PACKAGEID = PKG.PACKAGEID
			WHERE
			  MC.CUSTOMERID IS NOT NULL
			GROUP BY
			  C.CUSTOMERID
		  ) AS EARNINGS
		  JOIN (
				SELECT
				  C.CUSTOMERID,
                  SUM(DE.AMOUNT) SPENDAMOUNT
				FROM
				  CUSTOMERS C
				  JOIN COMPLAINT COMP ON C.CUSTOMERID = COMP.CUSTOMERID
				  JOIN DETAILEXPENSES DE ON COMP.COMPLAINTID = DE.COMPLAINTID
				GROUP BY
				  C.CUSTOMERID
			  ) AS EXPENSES ON EARNINGS.CUSTOMERID = EXPENSES.CUSTOMERID

	END TRY
	BEGIN CATCH
		THROW;
END CATCH;
END